export const TOKENS = {
  AuthRemoteDS: Symbol("AuthRemoteDS"),
  AuthRepo: Symbol("AuthRepo"),
  LoginUC: Symbol("LoginUC"),
  SignupUC: Symbol("SignupUC"),
  LogoutUC: Symbol("LogoutUC"),
  GetCurrentUserUC: Symbol("GetCurrentUserUC"),
  ProductRemoteDS: Symbol("ProductRemoteDS"),
  ProductRepo: Symbol("ProductRepo"),
  AddProductUC: Symbol("AddProductUC"),
  UpdateProductUC: Symbol("UpdateProductUC"),
  DeleteProductUC: Symbol("DeleteProductUC"),
  GetProductsUC: Symbol("GetProductsUC"),
  GetProductByIdUC: Symbol("GetProductByIdUC"),
  CourseRemoteDS: Symbol("CourseRemoteDS"),
  CourseRepo: Symbol("CourseRepo"),
  GetAvailableCoursesUC: Symbol("GetAvailableCoursesUC"),
  GetCreatedCoursesUC: Symbol("GetCreatedCoursesUC"),
  GetEnrolledCoursesUC: Symbol("GetEnrolledCoursesUC"),
  CreateCourseUC: Symbol("CreateCourseUC"),
  JoinCourseUC: Symbol("JoinCourseUC"),
  // Category tokens
  CategoryRemoteDS: Symbol("CategoryRemoteDS"),
  CategoryRepo: Symbol("CategoryRepo"),
  GetCategoriesByCourseUC: Symbol("GetCategoriesByCourseUC"),
  CreateCategoryUC: Symbol("CreateCategoryUC"),
  UpdateCategoryUC: Symbol("UpdateCategoryUC"),
  DeleteCategoryUC: Symbol("DeleteCategoryUC"),
  GetGroupsByCategoryUC: Symbol("GetGroupsByCategoryUC"),
  CreateGroupUC: Symbol("CreateGroupUC"),
  UpdateGroupUC: Symbol("UpdateGroupUC"),
  DeleteGroupUC: Symbol("DeleteGroupUC"),
  AddStudentToGroupUC: Symbol("AddStudentToGroupUC"),
  RemoveStudentFromGroupUC: Symbol("RemoveStudentFromGroupUC"),
  // Groups tokens (separate feature)
  GroupRemoteDS: Symbol("GroupRemoteDS"),
  GroupRepo: Symbol("GroupRepo"),
  GetGroupsByCategoryUC_v2: Symbol("GetGroupsByCategoryUC_v2"),
  CreateGroupUC_v2: Symbol("CreateGroupUC_v2"),
  UpdateGroupUC_v2: Symbol("UpdateGroupUC_v2"),
  DeleteGroupUC_v2: Symbol("DeleteGroupUC_v2"),
  AddStudentToGroupUC_v2: Symbol("AddStudentToGroupUC_v2"),
  RemoveStudentFromGroupUC_v2: Symbol("RemoveStudentFromGroupUC_v2"),
  // Activity tokens
  ActivityRemoteDS: Symbol("ActivityRemoteDS"),
  ActivityRepo: Symbol("ActivityRepo"),
  GetActivitiesByCourseUC: Symbol("GetActivitiesByCourseUC"),
  GetActivitiesByCategoryUC: Symbol("GetActivitiesByCategoryUC"),
  CreateActivityUC: Symbol("CreateActivityUC"),
  UpdateActivityUC: Symbol("UpdateActivityUC"),
  DeleteActivityUC: Symbol("DeleteActivityUC"),
  // Submission tokens
  SubmissionRemoteDS: Symbol("SubmissionRemoteDS"),
  SubmissionRepo: Symbol("SubmissionRepo"),
  CreateSubmissionUC: Symbol("CreateSubmissionUC"),
  UpdateSubmissionUC: Symbol("UpdateSubmissionUC"),
  GetSubmissionByActivityAndStudentUC: Symbol("GetSubmissionByActivityAndStudentUC"),
} as const;
